import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  projectDetail,
  projectTable,
}: Readonly<{
  projectDetail: React.ReactNode;
  projectTable: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-blue-50 to-indigo-100`}
      >
        <div className="flex h-screen">
          <div className="w-1/2">{projectTable}</div>
          <div className="w-1/2">{projectDetail}</div>
        </div>
      </body>
    </html>
  );
}
